from flask import Flask, render_template, request, send_file, jsonify, make_response
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph, Frame, Spacer
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from PyPDF2 import PdfReader
import os, json, urllib.request

app = Flask(__name__)

# ✅ Fonte profissional — Baixa automaticamente se não existir
FONT_PATH = "DejaVuSans.ttf"
if not os.path.exists(FONT_PATH):
    print("🔽 Baixando fonte DejaVuSans...")
    url = "https://github.com/dejavu-fonts/dejavu-fonts/raw/version_2_37/ttf/DejaVuSans.ttf"
    urllib.request.urlretrieve(url, FONT_PATH)
    print("✅ Fonte baixada com sucesso!")

# ✅ Registrar a fonte
pdfmetrics.registerFont(TTFont('DejaVuSans', FONT_PATH))

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate_pdf', methods=['POST'])
def generate_pdf():
    try:
        data = request.get_json()
        title = data.get('title', '').strip()
        author = data.get('author', '').strip()
        description = data.get('description', '').strip()

        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # Margens
        margin_x = 60
        margin_y = 80

        # ✅ Estilos de texto profissionais
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Title'],
            fontName='DejaVuSans',
            fontSize=16,
            leading=20,
            alignment=1,
            spaceAfter=20
        )
        normal_style = ParagraphStyle(
            'NormalStyle',
            parent=styles['Normal'],
            fontName='DejaVuSans',
            fontSize=12,
            leading=18,
            textColor=colors.black
        )

        # ✅ Criar conteúdo
        story = []

        if title:
            story.append(Paragraph(f"<b>{title}</b>", title_style))
        if author:
            story.append(Paragraph(f"<b>Autor:</b> {author}", normal_style))
            story.append(Spacer(1, 10))
        if description:
            story.append(Paragraph(description.replace("\n", "<br/>"), normal_style))

        frame = Frame(margin_x, margin_y, width - 2 * margin_x, height - 2 * margin_y, showBoundary=0)
        frame.addFromList(story, c)

        # ✅ Marca d’água profissional no canto inferior direito
        watermark_text = "Generated by AutoPDF"
        c.saveState()
        c.setFont("DejaVuSans", 9)
        c.setFillGray(0.7, 0.2)  # Transparente e discreta
        c.drawRightString(width - 50, 30, watermark_text)
        c.restoreState()

        c.save()
        pdf = buffer.getvalue()
        buffer.close()

        response = make_response(pdf)
        response.headers['Content-Type'] = 'application/pdf'
        response.headers['Content-Disposition'] = 'inline; filename=generated.pdf'
        return response

    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/active_users', methods=['GET'])
def active_users():
    try:
        return jsonify({"active_users": 42})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    app.run(debug=True)
